# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'H5JOwkDPgDFL7JRUqVVf9TGGU'
  twitter_api_secret: '7eltcA4n3M7FgmMfIOa0hrLApB99wIQvkbaV2LEouQ8e2LE6M1'

development:
  secret_key_base: 97ab8a3624cdb42ad8359ccbd07bd9612f478968798fbd54404fb8add835dd3fb00631c4e73a402d2186501d46cb5928b23192b3d5ac7560a9b23bb6b690bae0
  <<: *default_twitter

test:
  secret_key_base: a42610e93c27398477f7620039f81bcba8465821089d947c5e13702f172dc485ce4212f3913bd59dc010a4022f3825dba8ef689d1f94490f082e50c16bc8fd4c
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
